config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'experiences#start'
  get '/login' => 'sessions#new'
  get '/home' => 'experiences#index'
  get '/signup' => 'users#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  post '/add_user' => 'trips#add_user'
  get "/trips/browse" => "trips#browse"
  post "/trips/browse" => "trips#browse"
  get "/trips/search" => "trips#search"
  post "/trips/search" => "trips#search"
  post "/friends/add" => "friends/add"
  post "/friends/reject" => "friends/reject"
  post "/friends/remove" => "friends/remove"
  get "/friends/search" => "friends/search"
  post "/friends/search" => "friends/search"
  resources :posts, only: [:new, :create, :edit, :update, :destroy]
  resources :items, only: [:new, :create, :edit, :update, :destroy]
  resources :friends, only: [:index, :create]
  resources :users
  resources :trips

  resources :rooms
  resources :bookings
  
  namespace :api do
    namespace :v1 do
      resources :bookings, only: [:create, :index]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :date, presence: true

    
    belongs_to :category 
    belongs_to :location
    has_and_belongs_to_many :users
    has_many :posts
    has_many :items
    
    accepts_nested_attributes_for :location

    def add_user(user)
        self.users.push(user)
    end
 
    def find_friends(user)
        potential = user.friends
        potential.select{|u| self.users.all.exclude?(u)}
    end

    def find_author
        author = User.find_by(id: self.author_id)
        if author
           return author
        else #random failsafe if author deletes profile
            newowner = self.users.sample
            self.owner_id = newowner.id
            self.save
            return newowner
        end
    end

    def self.by_name
        order(:name)
    end

    def self.by_date
        order(:date)
    end

    def self.by_category
        Trip.all.sort_by {|trip| trip.category.name}
    end

    def self.by_most_recent
        t = Trip.by_date
        t.first(5)
    end

    def self.by_location
        Trip.all.sort_by {|trip| trip.location.state}
    end

    def self.by_one_location location
        Trip.all.select{|trip| trip.location.city.downcase.include?(location)}
    end

    def self.by_one_category category
        Trip.all.select{|trip| trip.category.name.downcase.include? category}
    end

    def self.by_specific_name name
        Trip.all.select{|trip| trip.name.downcase.include? name}
    end

    def self.by_specific_user username
        trips = []
        users = User.all.select{|user| user.name.downcase.include?(username)}
        users.each do |user|
            if Trip.all.select{|trip| trip.users.include?(user)} == []
            else
            trips << Trip.all.select{|trip| trip.users.include?(user)}
            end
        end
        trips[0]
    end


    def location_attributes=(location_attributes)
        self.build_location(location_attributes)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
    
    def new
        @trip = Trip.new
        @trip.build_location
    end

    def create 
        author = User.find_by(id: session[:user_id])
        @trip = Trip.new(trip_params)
        @trip.author_id = author.id
        @trip.users << author
        @trip.save
        if @trip.save
            redirect_to trip_path(@trip)
        else
            render :new
            @trip.errors.full_messages.each do |msg|
                puts msg
            end
        end
    end

    def show
        require_logged_in
        @trip = Trip.find(params[:id])
    end

    def update
        @trip = Trip.find(params[:id])
        @trip.add_user(User.find_by(id: params[:trip][:user_ids]))
        if @trip.save
            redirect_to trip_path(@trip)
        else
            @trip.errors.full_messages.each do |msg|
                puts msg
            end
        end
    end

    def destroy
        @trip = Trip.find(params[:id])
        @trip.items.destroy_all
        @trip.posts.destroy_all
        @trip.destroy
        redirect_to '/home'
    end

    def browse
        case params[:type]
        when nil
            @trips = Trip.all
            render :browse
        when 'Name'
            @trips = Trip.by_name
            render :browse
        when 'Date'
            @trips = Trip.by_date
            render :browse
        when 'Location'
            @trips = Trip.by_location
            render :browse
        when 'Category'
            @trips = Trip.by_category
            render :browse
        when 'Recent'
            @trips = Trip.by_most_recent
            render :browse
        end
    end

    def search
        s = params[:search].downcase
        case params[:type]
        when 'Select'
            @trips = Trip.all
            render :browse
        when 'Trip Name'
            @trips = Trip.by_specific_name(s)
            render :browse
        when 'Location'
            @trips = Trip.by_one_location(s)
            render :browse
        when 'Category'
            @trips = Trip.by_one_category(s)
            render :browse
        when 'User'
            @trips = Trip.by_specific_user(s)
            render :browse
        end
    end

private

    def trip_params
        params.require(:trip).permit(:name, :description, :category_id, :location_id, :date, location_attributes: [:city, :state])
    end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/browse.html.erb
<% if @trips == [] || @trips == nil %>
    <main class="ui raised very padded text container segment">
        <h1 class="ui header">No Results Found</h1>
        <a class="ui mini positive button" href="/trips/new">Start your own?</a>
        <a class="ui mini teal button" href="/trips/browse">Back</a>
    </main>
    <img class="ui massive centered rounded image" src="https://images.unsplash.com/photo-1561363702-e07252da3399?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" alt="sad mountains">
    <% else %>
        <main class="ui two column doubling stackable grid container">
            <section class="column">
                <div class="ui teal segment">
                    <div class="ui basic segment">
                        <h4 class="ui header">Sort by:</h4>
                        <div class="ui fluid input">
                            <%= form_tag ({controller: 'trips', action: 'browse'}) do %>
                                <%= select_tag "type", raw("
                                    <option>Name</option>
                                    <option>Date</option>
                                    <option>Location</option>
                                    <option>Category</option>
                                    <option>Recent</option>"
                                ) %>
                                    <input class="ui mini basic button" type="submit" name="commit" value="Apply" data-disable-with="Apply">
                                    <% end %>
                        </div>
                    </div>
                    <div class="ui basic segment">
                        <h4 class="ui header">Search by:</h4>
                        <%= form_tag({controller: 'trips', action: 'search'}) do %>
                            <%= select_tag "type", raw("
                            <option>Select</option>
                            <option>Trip Name</option>
                            <option>User</option>
                            <option>Location</option>
                            <option>Category</option>"
                            ) %>
                                <div class="ui action input">
                                    <input type="text" name="search" id="search">
                                    <input class="ui mini basic button" type="submit" name="commit" value="Search" data-disable-with="Search">
                                </div>
                                <% end %>
                    </div>
                </div>
            </section>

            <section class="column">
                <% @trips.each do |trip| %>
                    <div class="ui vertical segment">
                        <h3 class="ui header">
                            <%= link_to  trip.name, trip_path(trip) %>
                        </h3>
                        <h5 class="ui header">
                            <%= trip.find_author.name %>
                        </h5>
                        <p class="ui segment">
                            <%= trip.description %>
                        </p>
                        <% if current_user.id == trip.author_id %>
                            <!-- <div class="ui buttons">
                                <button class="ui tiny button">
                                <= link_to  "Edit", edit_trip_path(trip) >
                            </button> -->
                            <button class="ui tiny button">
                                <%= link_to  "Delete Trip", trip_path(trip), method: :delete, data: { confirm: "Are you sure?" } %>
                            </button>
                    </div>
                    <% end %>
                        </div>
                        <% end %>
            </section>
        </main>
        <% end %>

app/views/trips/new.html.erb
<main class="ui teal raised very padded text container segment">
    <div class="ui basic segment">
        <h1 class="ui huge header">Create a New Trip</h1>
    </div>
    <%= form_for @trip do |f| %>
        <div class="ui basic segment">
            <div class="ui labeled fluid input">
                <div class="ui label">
                    Trip Name
                </div>
                <input type="text" name="trip[name]" id="trip_name">
            </div>
        </div>
        <div class="ui basic segment">
            <div class="ui labeled fluid input">
                <div class="ui label">
                    Description
                </div>
                <textarea name="trip[description]" id="trip_description"></textarea>
            </div>
        </div>
        <div class="ui basic segment">
            <div class="ui labeled fluid input">
                <div class="ui label">
                    Date and Time
                </div>
                <input type="datetime-local" name="trip[date]" id="trip_date">
            </div>
        </div>
        <div class="ui basic segment">
            <div class="ui labeled fluid input">
                <div class="ui label">
                    Category
                </div>
                <%= f.collection_select :category_id, Category.all, :id, :name %>
            </div>
        </div>
        <div class="ui basic segment">
            <div class="ui labeled fluid input">
                <div class="ui label">
                    Location
                </div>
                <%= f.fields_for :location do |location_builder| %>
                    <input type="text" name="trip[location_attributes][city]" id="trip_location_attributes_city" placeholder="City">
                    <%= location_builder.collection_select :state, State.all, :name, :name %>
                        <% end %>
            </div>
        </div>
        <div class="ui basic segment">
            <input class="ui positive button" type="submit" name="commit" value="Create Trip!" data-disable-with="create trip">
        </div>
        <% end %>
            <% if @trip.errors.any? %>
                <div class="ui padded text segment">
                    <div class="ui visible message">
                        <p>
                            <% @trip.errors.full_messages.each do |msg| %>
                                <li>
                                    <%= msg %>
                                </li>
                                <% end %>
                        </p>
                    </div>
                </div>
                <% end %>
</main>

app/views/trips/show.html.erb
<main class="ui two column doubling stackable grid container">
    <div class="column">
        <div class="ui basic segment">
            <h1 class="ui header">
                <%= @trip.name %>
            </h1>
        </div>
        <div class="ui raised padded text segment">
            <h3>Description:</h3>
            <p>
                <%= @trip.description %>
            </p>
            <h3>Date/Time:</h3>
            <p>
                <%= @trip.date.strftime("%m %d %Y at %H:%M") %>
            </p>
        </div>
        <div class="ui basic segment">
            <h4 class="ui header">Crew:</h4>
            <div class="ui four column doubling stackable grid container">
                <% @trip.users.all.each do |user| %>
                    <span class="column">
                        <div class="ui attached segment">
                            <%= link_to  user.name, user_path(user) %>
                        </div>
                    </span>
                    <% end %>
            </div>
        </div>
        <div class="ui floated basic segment">
            <h3>Location:</h3>
            <a href="https://www.google.com/maps/place/<%=@trip.location.city%>,+<%=@trip.location.state%>" target="blank">
            <img src="https://maps.googleapis.com/maps/api/staticmap?markers=<%=@trip.location.latitude%>,<%=@trip.location.longitude%>&zoom=12&size=300x300&key=AIzaSyDiwsNArA4301pF8vLvRgWmS9u40Go5L2k">
        </a>
        </div>
    </div>
    <% if @trip.users.include?(current_user) %>
        <div class="column">
            <div class="ui basic segment"></div>
            <% if @trip.find_friends(current_user).any? %>
                <div class="ui segment">
                    <h3>Invite Friends!</h3>
                    <%= form_for @trip do |f| %>
                        <%= f.collection_select :user_ids, current_user.friends.all.select{|u| @trip.users.all.exclude?(u)}, :id, :name %>
                            <input class="ui tiny basic button" type="submit" name="commit" value="Invite Friend" data-disable-with="Invite Friend">
                            <% end %>
                </div>
                <% else %>
                    <div class="ui basic segment"></div>
                    <% end %>
                        <div class="ui segment">
                            <h3 class="ui header">Add Item To Packing List</h3>
                            <%= form_tag({controller: 'items', action: 'create', method: 'post'}) do %>
                                <input type="hidden" name="trip_id" value="<%= @trip.id %>">
                                <div class="ui input">
                                    <input type="text" name="name" placeholder="Hiking Boots...">
                                </div>
                                <button class="ui tiny basic button" type="submit">Add Item</button>
                                <% end %>
                        </div>
                        <div class="ui segment">
                            <h3 class="ui header">Add Comment</h3>
                            <%= form_tag({controller: 'posts', action: 'create', method: 'post'}) do %>
                                <input type="hidden" name="trip_id" value="<%= @trip.id %>">
                                <div class="ui input">
                                    <input type="text" name="body">
                                </div>
                                <button class="ui tiny basic button" type="submit">Comment</button>
                                <% end %>
                                    <% if @trip.posts.any? %>
                                        <% @trip.posts.reverse.each do |post| %>
                                            <div class="ui vertical segment">
                                                <img class="ui avatar image" src="<%=post.user.photo %>" alt="<%=post.user.name%>">
                                                <span class="ui header">
                                                <%= post.user.name %>
                                            </span>
                                                <p>
                                                    <%= post.body %>
                                                </p>
                                                <% if session[:user_id] == post.user.id %>
                                                    <div class="ui buttons">
                                                        <button class="ui mini button">
                                                        <%= link_to  "Delete Comment", post_path(post), method: :delete %>
                                                    </button>
                                                    </div>
                                                    <% end %>
                                            </div>
                                            <% end %>
                        </div>
        </div>
        <% end %>
</main>
<section class="ui two column doubling stackable grid container">
    <div class="column">
        <div class="ui segment">
            <h4 class="ui header">Packing list:</h4>
            <ul class="ui large middle animated aligned divided list">
                <% @trip.items.reverse.each do |item| %>
                    <p class="item">
                        <a href="https://www.amazon.com/s?k=<%=item.name%>" target="blank">
                            <%=item.name%>
                        </a>
                        <button class="ui right floated mini button">
                            <%= link_to  "Remove", item_path(item), method: :delete %>
                        </button>
                    </p>
                    <% end %>
            </ul>
        </div>
    </div>
</section>
<% end %>