config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'experiences#start'
  get '/login' => 'sessions#new'
  get '/home' => 'experiences#index'
  get '/signup' => 'users#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  post '/add_user' => 'trips#add_user'
  get "/trips/browse" => "trips#browse"
  post "/trips/browse" => "trips#browse"
  get "/trips/search" => "trips#search"
  post "/trips/search" => "trips#search"
  post "/friends/add" => "friends/add"
  post "/friends/reject" => "friends/reject"
  post "/friends/remove" => "friends/remove"
  get "/friends/search" => "friends/search"
  post "/friends/search" => "friends/search"
  resources :posts, only: [:new, :create, :edit, :update, :destroy]
  resources :items, only: [:new, :create, :edit, :update, :destroy]
  resources :friends, only: [:index, :create]
  resources :users
  resources :trips

  resources :rooms
  resources :bookings
  
  namespace :api do
    namespace :v1 do
      resources :bookings, only: [:create, :index]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ActiveRecord::Base

	enum room_type: ["Deluxe Rooms", "Luxury Rooms", "Luxury suites","Presidential Suites"]

	belongs_to :room
  belongs_to :user

  before_validation :rooms_are_available

	validate :last_date_greater_than_start_date_and_smaller_six_month
  validates :user_id, :start_date, :last_date, presence: true
  validates_format_of :start_date, :last_date, :with => /\d{4}\-\d{2}\-\d{2}/, :message => "^Date must be in the following format: mm/dd/yyyy"


  def last_date_greater_than_start_date_and_smaller_six_month 
    if dates_is_blank?
      return true
    elsif Date.today > start_date.to_date
      errors.add(:start_date, "check in date should be greater or equal to today's date")
    # last_date should be smaller than 6 months
    elsif Date.today + 6.months < last_date.to_date 
      errors.add(:last_date, "Check out date should be smaller than 6 months")
    # last_date should be greater than start_date
    elsif last_date.to_date < start_date.to_date
      errors.add(:last_date, "check out date should be greater than Check in Date")
    end
  end

	# get the all the room_id which room are booked in between start_date and last_date
  def self.excluded_id(start_date,last_date)
    # if array is empty return  true else return the array
    if (b= Booking.where("Date(start_date) < ? AND Date(last_date) > ? ", last_date,start_date).collect(&:room_id)).empty?
      return false
    else
      return b
    end
  end

  def rooms_are_available
    if dates_is_blank?
      return true
    # last_date should be smaller than 6 months
  	elsif (rooms = Room.avail_rooms(start_date, last_date, room_type).limit(1)).length > 0
  		self.room_id = rooms.first.id
		else

			errors.add(:num_of_user, "Rooms are not available #{room_type}")
		end
  end

  def dates_is_blank?
    if start_date.blank? || last_date.blank?
      return true
    end
  end

  def room_type_int
    self.class.room_types[self.room_type]
  end
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true 
    has_many :trips

    def self.by_name
        order(:name)
    end

end

app/models/item.rb
class Item < ApplicationRecord
    validates :name, presence: true
    belongs_to :trip
    belongs_to :user
end

app/models/location.rb
class Location < ApplicationRecord
    validates :city, presence: true
    validates :state, presence: true
    has_many :trips
    geocoded_by :address
    after_validation :geocode

    def self.by_city
        order(:city)
    end

    def address
        [city, state].compact.join(', ')
    end

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :trip


    def self.by_date
        order(:created_at)
    end

    def self.by_specific_user user
        Post.select{|p| p.user_id == user.id}
    end

    def self.by_trip trip
        Post.select{|p| p.trip_id == trip.id}
    end
    
end

app/models/room.rb
class Room < ActiveRecord::Base
	enum room_type: ["Deluxe Rooms", "Luxury Rooms", "Luxury suites","Presidential Suites"]
	has_and_belongs_to_many :bookings

  def self.avail_rooms(start_date, last_date, room_type)
  	if Booking.excluded_id(start_date, last_date)
  		self.where("room_type = ? AND id NOT IN (?)", Room.room_types[room_type], Booking.excluded_id(start_date, last_date))
  	else
  		self.where("room_type = ?", Room.room_types[room_type])
  	end
  end

  def room_type_int
    self.class.room_types[self.room_type]
  end
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :date, presence: true

    
    belongs_to :category 
    belongs_to :location
    has_and_belongs_to_many :users
    has_many :posts
    has_many :items
    
    accepts_nested_attributes_for :location

    def add_user(user)
        self.users.push(user)
    end
 
    def find_friends(user)
        potential = user.friends
        potential.select{|u| self.users.all.exclude?(u)}
    end

    def find_author
        author = User.find_by(id: self.author_id)
        if author
           return author
        else #random failsafe if author deletes profile
            newowner = self.users.sample
            self.owner_id = newowner.id
            self.save
            return newowner
        end
    end

    def self.by_name
        order(:name)
    end

    def self.by_date
        order(:date)
    end

    def self.by_category
        Trip.all.sort_by {|trip| trip.category.name}
    end

    def self.by_most_recent
        t = Trip.by_date
        t.first(5)
    end

    def self.by_location
        Trip.all.sort_by {|trip| trip.location.state}
    end

    def self.by_one_location location
        Trip.all.select{|trip| trip.location.city.downcase.include?(location)}
    end

    def self.by_one_category category
        Trip.all.select{|trip| trip.category.name.downcase.include? category}
    end

    def self.by_specific_name name
        Trip.all.select{|trip| trip.name.downcase.include? name}
    end

    def self.by_specific_user username
        trips = []
        users = User.all.select{|user| user.name.downcase.include?(username)}
        users.each do |user|
            if Trip.all.select{|trip| trip.users.include?(user)} == []
            else
            trips << Trip.all.select{|trip| trip.users.include?(user)}
            end
        end
        trips[0]
    end


    def location_attributes=(location_attributes)
        self.build_location(location_attributes)
    end
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :name, uniqueness: true
    validates :email, presence: true
    validates :email, uniqueness: true

    has_secure_password
    has_friendship

    has_and_belongs_to_many :trips
    has_many :posts
    has_many :items

    has_many :bookings


    enum role: [:user, :admin]

    def friends?
        self.friends
    end

    def friend_requests?
        self.requested_friends.any?
    end

    def requested_friends?
        self.pending_friends.any?
    end

    def invite_friend(user)
        self.friend_request(user)
    end

    def not_friends
        potential = []
        User.all.each do |user|
            if(self.friends_with?(user) != true && self != user && self.friends.include?(user) != true && self.pending_friends.include?(user) != true && self.requested_friends.include?(user) != true)
                potential << user
            end
        end
        potential
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
	def admin?
		current_user == User.first
	end

	def authorize
    unless admin?
      flash[:error] = "unauthorized access"
      redirect_to home_path
      false
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/browse_helper.rb
module BrowseHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Tourmate</title>
    <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

            <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
                <%= javascript_include_tag 'application' %>
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">


                    <%= javascript_include_tag("jquery.flexslider")%>

                    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<!---- start-smoth-scrolling---->

	<script type="text/javascript">
	      jQuery(document).ready(function($) {
	        $(".scroll").click(function(event){   
	          event.preventDefault();
	          $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
	        });
	      });
	    </script>
	<!--start-smoth-scrolling-->
                </head>

<body>
    <%=  render partial = "shared/navbar"%>
    <%= yield %>
</body>

</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <title>TourMate</title>
    <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

            <%= stylesheet_link_tag    'application', media: 'all' %>
                <%= javascript_include_tag 'application' %>
                    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">
</head>

<body>
    <%= render partial ="shared/navbar"%>
    <%= yield %>

    <%= render  partial = "home/slider" %>
    <%= render  partial = "home/how" %>
    <%= render  partial =  "home/why"%>
</body>

</html>

app/views/shared/_navbar.html.erb
<nav class="ui secondary pointing menu">
    <div class="ui basic segment" style="padding:0%; margin-block:auto;">
        <a href="/"> <img class="" src="https://tourmatetours.com/wp-content/uploads/2022/01/tourmate_tours_logo_rectangle-removebg-preview.png" alt="Tourmate" width="40" height="30"></a>
    </div>
    <% if !logged_in?%>
      <a href="/" class="item ">Home</a>
      <a href="/login" class="item" style="text-align: right;">Sign In</a>
      <a href="/signup" class="item">Sign Up</a>
    <%end%>
      <% if logged_in? %>
        <a class="item" href="/home">My Trips</a>
        <% if current_user.friend_requests? %>
            <a class="item" href="<%= friends_path %>">Friends
          <div class="floating ui red circular label"><%=current_user.requested_friends.count%></div></a>
            <% else %>
                <a class="item" href="<%= friends_path %>">Friends</a>
                <% end %>
                    <a class="item" href="<%= user_path(current_user)%>">Profile</a>
                    <a class="item" href="/trips/browse">Browse</a>
                    <%= link_to 'Bookings', bookings_path,class: "item" %>
                    <%= link_to 'Rooms', rooms_path,class: "item" %>
                    <% end %>


                        <div class="right menu">
                            <div class="item">
                                <% if session[:user_id] %>
                                    <%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
                                        <input class="ui basic button" type=submit value='logout'>
                                        <% end %>
                                            <% end %>
                            </div>
                        </div>
</nav>



<!-- script-for-menu -->
  <!-- script-for-menu -->
  <script>
    $("span.menu").click(function(){
      $(" ul.navig").slideToggle("slow" , function(){
      });
    });
  </script>