config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root 'experiences#start'
  get '/login' => 'sessions#new'
  get '/home' => 'experiences#index'
  get '/signup' => 'users#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  post '/add_user' => 'trips#add_user'
  get "/trips/browse" => "trips#browse"
  post "/trips/browse" => "trips#browse"
  get "/trips/search" => "trips#search"
  post "/trips/search" => "trips#search"
  post "/friends/add" => "friends/add"
  post "/friends/reject" => "friends/reject"
  post "/friends/remove" => "friends/remove"
  get "/friends/search" => "friends/search"
  post "/friends/search" => "friends/search"
  resources :posts, only: [:new, :create, :edit, :update, :destroy]
  resources :items, only: [:new, :create, :edit, :update, :destroy]
  resources :friends, only: [:index, :create]
  resources :users
  resources :trips

  resources :rooms
  resources :bookings
  
  namespace :api do
    namespace :v1 do
      resources :bookings, only: [:create, :index]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

    def start
        if logged_in?
            redirect_to '/home'
        else
            render layout: "landing"
        end
    end

    def index
        require_logged_in
        @user = User.find_by(id: session[:user_id])
    end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/index.html.erb
<section id="left_banner">
    <div class="ui raised segment">
        <img class="ui tiny avatar image" src="<%=@user.photo %>" alt="<%=@user.name%>">
        <span class="ui header">
            <%= @user.name %>
        </span>
        <a class="ui primary right floated positive button" href="/trips/new">New Trip</a>
    </div>
    <div class="ui teal text container raised segment">
        <h3 class="ui teal center aligned header">Your Trips</h3>
    </div>
</section>
<% if @user.trips.any? %>
    <main class="ui raised very padded text container segment">
        <section>
            <% @user.trips.all.reverse.each do |trip| %>
                <div class="ui vertical segment">
                    <h3 class="ui header">
                        <%= link_to  trip.name, trip_path(trip) %>
                    </h3>
                    <h5 class="ui header">
                        <%= trip.find_author.name %>
                    </h5>
                    <p class="ui segment">
                        <%= trip.description %>
                    </p>
                    <% if @user.id == trip.author_id %>
                        <!-- <div class="ui buttons">
                            <button class="ui tiny button">
                        <= link_to  "Edit", edit_trip_path(trip) >
                    </button> -->
                        <button class="ui tiny button">
                        <%= link_to  "Delete Trip", trip_path(trip), method: :delete, data: { confirm: "Are you sure?" } %>
                    </button>
                </div>
                <% end %>
                    </div>
                    <% end %>
        </section>
    </main>
    <% else %>

        <% end %>

app/views/experiences/start.html.erb
<main class="ui basic segment">
    <body id="welcome_body">
    <div id="welcome_banner" class="ui container segment">
        <img class="ui centered image" src="https://images-na.ssl-images-amazon.com/images/I/91Aej86NHhL.png" alt="Tourmate" width="1000" height="250">
    </div>
    <div class="ui hidden divider"></div>
    
    <div class="ui hidden divider"></div>
    <div class="ui teal raised very padded text container segment">
        <h3 class="ui centered large header">The Ultimate Trip Planner</h3>
            <div class="ui clearing container segment">
                <span class="ui basic left floated segment"><p class="ui header">Have an account?</p></span>
                <a class="ui large right floated positive button" href='/login'>Login!</a>
            </div>
            <div class="ui clearing container segment">
                <span class="ui basic left floated segment"><p class="ui header">Or get started here!</p></span>
                <a class="ui large right floated teal button" href='/signup'>Sign Up!</a>
            </div>
    </div>
    </body>
</main>